### ISSUE TITLE
Cannot find module './data/lahore.json'

### ISSUE THREAD

**Issue by msaaddev** [ahmadawais/ramadan-cli#1]
When I tried to run the CLI, I got this error. 

![error](https://i.imgur.com/frbEjc6.png)

**Comment by webribs** [comment]
Getting the same issue

**Comment by ahmadawais** [comment]
🤦‍♂️ Dang man.

Should be fine now.

🔗 https://github.com/ahmadawais/ramadan-cli/releases/tag/1.2.0
🔗 https://www.npmjs.com/package/ramadan-cli
