### ISSUE TITLE
Issue when running `npx ramadan-cli`

### ISSUE THREAD

**Issue by akramsaouri** [ahmadawais/ramadan-cli#3]
![Screen Shot 2020-04-24 at 21 41 18](https://user-images.githubusercontent.com/16223384/80259247-a7eee100-8674-11ea-8825-37089baa6400.png)

I'm getting `Cannot find module 'cli-table3'` error when running `npx ramadan-cli`

Node version:  `13.7.0`
npx version: `6.14.4`
npm version: `6.14.4`

(also ramadan mubarak 🙏 )

**Comment by ahmadawais** [comment]
log-symbols

**Comment by ahmadawais** [comment]
Already, fixed. Thanks for the report. Apparently I'm asleep lol.
